### ISSUE TITLE
Temel kullanım

### ISSUE THREAD

**Issue by pseudozach** [linuxgemini/node-ininal#2]
Merhaba, 
Elinize sağlık çok güzel yazmışsınız.
Kullanım ile ilgili kısa/basit bir readme eklemeniz mümkün mü?
Birkaç temel komut örneği bile olsa başlamak için faydalı olur.

**Comment by linuxgemini** [comment]
Merhaba,

Yakın zamanda wrapper'ı tamamlamayı planlıyorum. Bitirdikten sonra `README.md` dosyasını güncelleyeceğim.

**Comment by pseudozach** [comment]
Eklediğinizde kullanıp test etmeyi planlıyorum, katkıda bulunmaya çalışırım elimden geldiği kadar.

**Comment by linuxgemini** [comment]
Üzerinden 1 koca yıl geçti ama sonunda bitti. README'yi okuyabilirsiniz.
